server:
  port: 8080

spring:
  application:
    name: ewm-main-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/ewm
    username: ewm_user
    password: "12345"
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  name: ewm-main-service

stats-server:
  url: http://stats-server:9090

logging:
  level:
    org.springframework.web: DEBUG
    ru.practicum: DEBUG
    org.hibernate.SQL: DEBUG